defmodule Arbiter.Tasks do
  @moduledoc """
  Ash domain for the task ledger.

  Holds workspaces, issues, dependencies, and audit events. This module
  is the entry point for code that creates / reads / updates tasks — call
  through `Ash` (e.g. `Ash.create(Arbiter.Tasks.Workspace, attrs)`).

  Resources land here as they're built across the gte-* tasks:

    * `Arbiter.Tasks.Workspace` — gte-P1 (this task) — workspace with config JSON
      (tracker config). Default workspace ships a `:none` tracker.
    * `Arbiter.Tasks.Issue` — gte-002 — Ash issue resource with the lifecycle `state` FSM, audit
      via paper_trail, tracker_type/tracker_ref fields. A task can be a *parent*
      of other tasks via `:parent_of` dependency edges; it then rolls up
      `{child_closed, child_total}` progress and optionally auto-closes when all
      its children are done (the `auto_close` flag).
    * `Arbiter.Tasks.Dependency` — gte-003 — task-to-task edges (blocks, depends_on,
      parent_of). Write through `Arbiter.Tasks.Dependencies` (bd-apj0gq), the
      facade that owns the cycle / cross-workspace / auto-close guards — never
      `Ash.create(Dependency, …)` directly from a call site.
  """

  use Ash.Domain

  resources do
    resource Arbiter.Tasks.Workspace
    # AshPaperTrail version rows for Workspace (bd-9j6is7); config + actor
    # history, queryable via Arbiter.Tasks.Workspace.Version.
    resource Arbiter.Tasks.Workspace.Version
    resource Arbiter.Tasks.Issue
    # Auto-generated by AshPaperTrail for Issue. Tracks every create/update with
    # diff + actor; queryable via Arbiter.Tasks.Issue.Version.
    resource Arbiter.Tasks.Issue.Version
    resource Arbiter.Tasks.Dependency
    # Auto-generated by AshPaperTrail for Dependency (bd-apj0gq). Records every
    # edge create/destroy with the endpoints + type snapshotted on the row.
    resource Arbiter.Tasks.Dependency.Version
    # bd-cq1wsp: one row per stretch of a ticket's attention, for reports.
    resource Arbiter.Tasks.AttentionSpan
    # One row per change of a ticket's lifecycle state (bd-5gkqdr), written by
    # triggers on `issues`; the history every report reads.
    resource Arbiter.Tasks.TicketTransition
    # bd-54m4vv: append-only trail of ticket-declared permissions (G12).
    resource Arbiter.Tasks.PermissionEvent
  end

  require Ash.Query

  @doc """
  Per-bucket child breakdown + the `needs_you` attention signal for `epics`,
  keyed by epic id.

  The read model behind `/epics` (bd-2wmxt5). See `Arbiter.Tasks.EpicRollup`
  for the bucket definitions and the `needs_you` rules (bd-58z2tu).
  """
  @spec epic_rollups([Arbiter.Tasks.Issue.t() | String.t()]) ::
          %{String.t() => Arbiter.Tasks.EpicRollup.t()}
  defdelegate epic_rollups(epics), to: Arbiter.Tasks.EpicRollup, as: :for_epics

  @doc """
  How many epics are not closed — the number on the "Epics" nav badge.
  """
  @spec open_epic_count() :: non_neg_integer()
  def open_epic_count do
    epic = :epic
    closed = :closed

    Arbiter.Tasks.Issue
    |> Ash.Query.filter(issue_type == ^epic and state != ^closed)
    |> Ash.count!()
  end
end
