defmodule Arbiter.Grok.AuthProvider do
  @moduledoc """
  How a grok worker gets its credential (bd-9p4lx9): the spawn-env half of
  `Arbiter.Grok.CredentialBroker`.

  `spawn_env/2` returns the credential-related environment for one worker's
  grok process. Two sources, never both:

    * **`XAI_API_KEY`** when one is configured (`:api_key_ref`, a
      `Arbiter.Agents.CredentialsRef` ref such as `"env:XAI_API_KEY"` or
      `"secret:xai"`). A paid console key is the operator's stated alternative to
      the free-tier login; grok prefers it whenever no session token is active,
      and the per-worker `GROK_HOME` has none. A configured ref that does not
      resolve is an error, not a quiet fall-back to the operator's login: the
      two bill differently.
    * **`GROK_AUTH_PROVIDER_COMMAND`** otherwise: grok's documented external
      auth provider. It is a generated wrapper script, `<GROK_HOME>/arbiter-grok-token`,
      that `exec`s `arb grok-token`. grok runs it with its own environment (so
      the worker's `ARB_TOKEN` / `ARB_HOST`, and `GROK_AUTH_EXPIRED=1` on a
      refresh) and expects `{"access_token", "expires_in"}` on stdout. The command
      asks the Arbiter server, which answers from `CredentialBroker.fetch_token/2`;
      the worker never sees the refresh token or the canonical `auth.json`.

  The script lives under the worker's own `GROK_HOME` (inside the worker's
  bound `HOME`), not `/tmp`: `Arbiter.Worker.Jail` mounts a private `--tmpfs /tmp`
  and anything the host wrote there is invisible to the jailed process. It is
  a bare path so grok has no argv to mis-split, and it holds no credential.

  Each source also removes the other's variable from the inherited environment
  (`value = false`), so a stray `XAI_API_KEY` or `GROK_AUTH_PROVIDER_COMMAND` in
  the server's own environment cannot leak into, or override, a worker.
  """

  alias Arbiter.Agents.CredentialsRef

  @script_name "arbiter-grok-token"

  @type env :: [{String.t(), String.t() | false}]

  @doc """
  The credential env for a worker whose `GROK_HOME` is `grok_home`.

  Options: `:api_key_ref` (default: `config :arbiter, :grok_broker, api_key_ref:`),
  `:config` (a raw config map for `secret:` refs), `:arb_path` (default: `arb` on
  `PATH`).
  """
  @spec spawn_env(String.t(), keyword()) ::
          {:ok, env()} | {:error, :arb_not_found | {:api_key_unresolved, String.t()}}
  def spawn_env(grok_home, opts \\ []) do
    case api_key_ref(opts) do
      nil -> broker_env(grok_home, opts)
      ref -> api_key_env(ref, opts)
    end
  end

  @doc "The wrapper script's file name under a worker's `GROK_HOME`."
  @spec script_name() :: String.t()
  def script_name, do: @script_name

  defp api_key_env(ref, opts) do
    case CredentialsRef.resolve(ref, Keyword.get(opts, :config, %{})) do
      {:ok, key} ->
        {:ok, [{"XAI_API_KEY", key}, {"GROK_AUTH_PROVIDER_COMMAND", false}]}

      _unresolved ->
        {:error, {:api_key_unresolved, ref}}
    end
  end

  defp broker_env(grok_home, opts) do
    arb = Keyword.get_lazy(opts, :arb_path, fn -> System.find_executable("arb") end)

    with true <- is_binary(arb) and File.regular?(arb),
         {:ok, script} <- install_script(grok_home, arb) do
      {:ok, [{"GROK_AUTH_PROVIDER_COMMAND", script}, {"XAI_API_KEY", false}]}
    else
      false -> {:error, :arb_not_found}
      {:error, _} = error -> error
    end
  end

  defp install_script(grok_home, arb) do
    script = Path.join(grok_home, @script_name)

    body =
      "#!/bin/sh\n# Generated by Arbiter (bd-9p4lx9). Holds no credential.\nexec #{quote_sh(arb)} grok-token\n"

    with :ok <- File.mkdir_p(grok_home),
         :ok <- File.write(script, body),
         :ok <- File.chmod(script, 0o755) do
      {:ok, script}
    end
  end

  defp quote_sh(path), do: "'" <> String.replace(path, "'", "'\\''") <> "'"

  defp api_key_ref(opts) do
    ref =
      Keyword.get_lazy(opts, :api_key_ref, fn ->
        :arbiter |> Application.get_env(:grok_broker, []) |> Keyword.get(:api_key_ref)
      end)

    if is_binary(ref) and ref != "", do: ref
  end
end
