defmodule Arbiter.Agents.Claude.ConfigDir do
  @moduledoc """
  An isolated `CLAUDE_CONFIG_DIR` for worker (implementer / reviewer) runs.

  ## Why

  Workers are spawned with `claude --print` inside a worktree. By default the
  child inherits the **host operator's** user-level config dir (`~/.claude`),
  which loads the operator's personal `~/.claude/CLAUDE.md`. On a developer
  install that file routinely carries personal memory — including, on this
  install, a *roleplay persona*. That persona bleeds into the worker's output:
  a REVIEWER once emitted `VERDICT: REQUEST_CHANGES` followed only by a
  theatrical flourish and **no actual findings**, stalling the gate and burning
  a full review pass. It is non-deterministic and silent (bd-3y2mda).

  The fix is to run workers against a *clean*, Arbiter-owned config dir that
  does **not** contain the operator's persona memory — so the worker's context
  is task-focused regardless of what the host operator keeps in `~/.claude`.

  ## How

  We point the spawn at a stable, Arbiter-managed directory via the
  `CLAUDE_CONFIG_DIR` env var (`Arbiter.Agents.Claude.spawn_env/1` and the
  ReviewGate's reviewer/implementer spawns both consult `env/1`). The directory is
  seeded **idempotently** on each spawn with the *minimum* a functioning worker
  needs — and nothing personal:

    * `.credentials.json` is **never** carried over — not linked, not copied
      (bd-80ecol). A worker authenticates with its own setup token
      (`CLAUDE_CODE_OAUTH_TOKEN`, injected by `env/1`) or an API key; a stale
      copy left by an older build is removed. See "Worker OAuth tokens" below.
    * `settings.json` is **generated by us** from the install-wide
      `Arbiter.Agents.SecurityPolicy.default/0` (via
      `Arbiter.Agents.Claude.Security`) — a hardened, non-empty-deny baseline.
      It is **never** symlinked from the operator's `~/.claude`, so the
      worker does **not** inherit the operator's personal permission posture
      (historically `defaultMode: auto` with an *empty* deny list). This is
      the floor; workspace-aware spawns layer the per-domain policy on top via
      `claude --settings` (bd-9u10op).
    * `CLAUDE.md` is **written by us** — a short, task-focused worker memory
      that also explicitly forbids roleplay/persona output. The operator's
      personal `CLAUDE.md` / `CLAUDE.local.md` are **never** linked, so they
      cannot load.

  Everything else the operator keeps in `~/.claude` (personal skills, agents,
  plugins, project history, …) is intentionally absent: a worker should run on
  a clean slate. The worker's own session state (history, projects) accumulates
  here, kept apart from the operator's.

  ## Worker OAuth tokens — no operator credentials, ever (bd-6umoh9, bd-bw3466, bd-80ecol)

  Seeding a worker a copy of the operator's `.credentials.json` is actively
  harmful: Claude rotates an interactive grant's refresh token on every
  refresh, so both holders race and whichever refreshes first revokes the
  other's copy — which is what forced the operator to `/login` repeatedly.
  bd-6umoh9/bd-bw3466 stopped seeding once a worker token was configured;
  bd-80ecol removed the remaining fallback ("mode B": copy the operator's
  file when *no* token resolves), because a revoked account credential or a
  workspace that lost its account join silently brought the lockout back.
  A spawn with no token now carries no Claude login at all, and
  `Arbiter.Agents.Claude.CredentialCheck` is what keeps that from being a
  silent 401: the dispatch guard refuses it with an escalation naming the fix,
  the watchdog probe declines to run, and `arb server doctor` lists the gap.

  The token is configured the per-workspace way — `oauth_token/1` reads the
  spawn's workspace `worker_env` (encrypted at rest), or (with provider
  accounts enabled) the workspace's joined account credential. With the flag
  off, the pre-P4 chain underneath the workspace token — the server process
  environment (bd-6umoh9), then the install-wide-unambiguous workspace token
  for a workspace-less spawn (bd-bw3466) — is **kept in place**, per the
  operator's ruling on PR #1947 (bd-cblemv round 2): v0.1.68's release notes
  promised flag-off equals v0.1.67 behavior, and an unmigrated install (this
  includes ones that have never run `mix arbiter.accounts.migrate`) still
  needs it for workspace-less spawns. Only once `:provider_accounts_enabled`
  is on for good does the account join become the one path
  (`Arbiter.Accounts.Credentials.install_credential/1`) and the legacy chain
  get deleted (the "flip" release).

  Note the config directory is **install-wide** — one shared
  `~/.cache/arbiter/worker-claude` for every workspace. A workspace-less spawn
  (the fleet-wide `CredentialWatchdog` probe, the quota probe, a code-review
  check) runs against that same directory. With provider accounts enabled
  that spawn takes the install-wide account credential (`oauth_token/1`);
  with the flag off it falls through the legacy chain (server env, then the
  install-wide-unambiguous workspace token), and carries no credential if
  that chain, too, comes up empty.

  bd-bw3466's invariant was **seeding suppressed ⟺ token injected**, so a
  spawn never had neither. With mode B gone the seed is always suppressed, so
  "neither" is now possible by design — and the hazard that invariant guarded
  against still applies: the `CredentialWatchdog` probe
  (`Preflight.check(adapter, [])`, no workspace) running with no credential
  would 401, be classified `:auth_expired`, and refuse *every* Claude dispatch
  with a false expiry. `Arbiter.Agents.Claude.auth_probe_argv/1` therefore
  asks `CredentialCheck` first and declines (a non-auth `Preflight` result
  the watchdog ignores) when no credential resolves. Any future change here
  must keep that pairing; `config_dir_workspace_test.exs` asserts the
  never-seeded half and `claude_test.exs` the probe half.

  ## Safety / degradation

  `ensure/1` is best-effort and self-guarding. If the directory or its memory
  file can't be created it returns `:error` and the caller falls back to the
  inherited (un-isolated) config — a working-but-persona worker beats a broken
  one. The inherited `ANTHROPIC_API_KEY` (if any) still flows through, since
  we override only `CLAUDE_CONFIG_DIR`.

  ## Config

    * `config :arbiter, :worker_isolate_config, boolean` — master switch
      (default `true`). The test suite sets it `false` so unit tests don't touch
      the real cache dir or shell out.
    * `config :arbiter, :worker_config_dir, "/path"` — override the directory
      (tests that *do* exercise isolation point this at a tmp dir).
  """

  alias Arbiter.Accounts
  alias Arbiter.Accounts.Credentials
  alias Arbiter.Accounts.MissingCredentialError
  alias Arbiter.Agents.Claude.Security
  alias Arbiter.Agents.CredentialsRef
  alias Arbiter.Tasks.Workspace

  require Logger

  # The operator config files `seed_credentials/2` copies — only ever for an
  # interactive session that explicitly chose mode B
  # (`ConfigDir.Interactive`); a worker dir never gets them (bd-80ecol).
  # Deliberately excludes:
  #   * CLAUDE.md / CLAUDE.local.md — the persona lives there (bd-3y2mda).
  #   * settings.json — the permission posture; we *generate* a hardened one
  #     instead of inheriting the operator's (bd-9u10op). See @settings_filename.
  @seed_links ~w(.credentials.json)

  @memory_filename "CLAUDE.md"
  @settings_filename "settings.json"

  @typedoc """
  How a caller names the workspace whose `worker_env` should be consulted:
  a loaded `Workspace` struct, its id (we load it), or `nil` when the caller
  legitimately has no workspace in hand (see `oauth_token/1`).
  """
  @type workspace_source :: Workspace.t() | String.t() | nil

  @oauth_token_var "CLAUDE_CODE_OAUTH_TOKEN"

  @doc """
  The env pairs to inject into a worker spawn: `[{"CLAUDE_CONFIG_DIR", dir}]`
  when isolation is enabled and the dir is ready (`[]` otherwise — inherit the
  host config unchanged), plus a `CLAUDE_CODE_OAUTH_TOKEN` pair — either
  `{"CLAUDE_CODE_OAUTH_TOKEN", token}` when a worker OAuth token (bd-2zigo1)
  is configured, or `{"CLAUDE_CODE_OAUTH_TOKEN", false}` (an explicit unset,
  understood by `Port.open`'s `{:env, …}` and by
  `Arbiter.Worker.ReleaseEnv.cmd/3`) when it is not — so a value inherited
  from the arbiter server's own process environment can never reach a spawn
  this function decided should carry no token. All three `ConfigDir`
  consumers (`claude.ex`, `worker/claude_session.ex`,
  `workflows/code_review/checks.ex`) call this single function, so the token
  (or its absence) reaches every worker spawn path rather than only the ones
  that separately remember to compose it in (bd-6umoh9).

  Pass the spawn's workspace (struct or id) so a token configured the
  per-workspace way — `worker_env`, encrypted at rest — is found. The
  zero-arity form is for callers with genuinely no workspace in hand; with
  provider accounts enabled it takes the install-wide account credential, so
  such a spawn is still authenticated (bd-bw3466); with the flag off it falls
  back to the server env and then the install-wide-unambiguous workspace
  token, the same as it did pre-P4. See `oauth_token/1` for the precedence.

  The **shape** of what this returns is fixed (§5 rows 16 and 20) — the pairs
  a spawn receives are the same before and after P3. With
  `:provider_accounts_enabled` on, the token pair's *value* is sourced from
  the workspace's provider account instead of its `worker_env` blob; see
  `oauth_token/1`.
  """
  @spec env(workspace_source()) :: [{String.t(), String.t() | false}]
  def env(workspace \\ nil) do
    config_pairs =
      case ensure(workspace) do
        {:ok, dir} -> [{"CLAUDE_CONFIG_DIR", dir}]
        _ -> []
      end

    config_pairs ++ oauth_token_pairs(workspace)
  end

  @doc """
  Whether a worker OAuth token (`CLAUDE_CODE_OAUTH_TOKEN`, bd-2zigo1) is
  configured for this spawn. When false the spawn has no setup token — and,
  since bd-80ecol, no copy of the operator's `.credentials.json` either; see
  `Arbiter.Agents.Claude.CredentialCheck` for what else can authenticate it.
  """
  @spec oauth_token_configured?(workspace_source()) :: boolean()
  def oauth_token_configured?(workspace \\ nil), do: not is_nil(oauth_token(workspace))

  @doc """
  The worker OAuth token for this spawn, or `nil`.

  ## With `:provider_accounts_enabled` on (P3, bd-aiodva; P4, bd-cblemv)

  A single join read (`docs/provider-account-design.md` §5 row 15): the
  spawn's workspace → its `workspace_provider_accounts` row → that account's
  **active** `provider_credentials` row for `CLAUDE_CODE_OAUTH_TOKEN`
  (`Arbiter.Accounts.Credentials`). The account is the answer; the workspace
  blob is not consulted.

  When the account has no credential for this workspace, the workspace's own
  `worker_env` is checked **only as a guard, not as a fallback**: if it still
  carries a token, the flip is about to take a credential away from this
  spawn, so this raises `Arbiter.Accounts.MissingCredentialError` rather than
  dispatching a worker that authenticates as nobody (acceptance 3). Once P4
  has run against every workspace that guard never fires, since `worker_env`
  no longer carries the moved keys at all (§7.5).

  A spawn with **no workspace in hand** has no join row to read: it takes the
  unambiguous install-wide *account* credential
  (`Arbiter.Accounts.Credentials.install_credential/1`) and answers `nil`
  when there is none. It never raises: the fleet-wide watchdog and quota
  probes run on this path and are not workspace configuration errors.

  ## With the flag off (an un-migrated install, or `ARBITER_PROVIDER_ACCOUNTS=0`)

  Since bd-cvvb02 the flag ships `:auto`, which resolves off for an install
  that still carries legacy credentials and has no migration record
  (`Arbiter.Accounts.Enablement`) — the population this chain exists for.

  Per the operator's ruling on PR #1947 (bd-cblemv round 2), the flag-off path
  keeps the full pre-P4 legacy chain verbatim, workspace-less spawns included
  — v0.1.68's release notes promised flag-off equals v0.1.67 behavior, and an
  install that has never run `mix arbiter.accounts.migrate` (this includes the
  coordinator's own production install as of this PR) still authenticates
  every spawn through it. Precedence — **most specific first**:

    1. `CLAUDE_CODE_OAUTH_TOKEN` in `workspace`'s encrypted `worker_env`
       (read via `Arbiter.Tasks.Workspace.worker_env_map/1`; the value is
       never serialised).
    2. `CLAUDE_CODE_OAUTH_TOKEN` in the arbiter server's own environment
       (`.arbiter.env` / the service unit) — the bd-6umoh9 behaviour.
    3. The install-wide workspace token, *only when it is unambiguous*: the
       single distinct `CLAUDE_CODE_OAUTH_TOKEN` value across every workspace
       that defines one. `nil` when zero or more than one distinct value
       exists (bd-bw3466).

  The workspace is the more specific configuration: an operator who sets a
  token on a workspace is stating what *that* workspace's workers authenticate
  as, and the server-wide var is the install default underneath it. Step 3
  exists because the config dir this token guards is **install-wide** (see the
  moduledoc): a spawn with no workspace in hand — the fleet-wide
  `CredentialWatchdog` probe, the quota probe, a code-review check — shares
  the directory whose `.credentials.json` a token-bearing spawn deletes.

  This whole chain is deleted only once `:provider_accounts_enabled` flips to
  `true` for good (the "flip" release) — see the module functions below for
  the pieces that exist for this path alone.

  Best-effort — a workspace that can't be loaded or whose store can't be
  decrypted falls through to the next source rather than raising into a spawn.
  """
  @spec oauth_token(workspace_source()) :: String.t() | nil
  def oauth_token(workspace \\ nil) do
    if Accounts.enabled?() do
      account_oauth_token(workspace)
    else
      legacy_oauth_token(workspace)
    end
  end

  # The pre-P4 chain, kept verbatim per the operator's ruling on PR #1947:
  # flag-off installs (this includes ones that have never run
  # `mix arbiter.accounts.migrate`) keep the full v0.1.68 behaviour, including
  # for workspace-less spawns. Deleted only when the flag flips to `true` for
  # good (the "flip" release).
  defp legacy_oauth_token(workspace) do
    workspace_oauth_token(workspace) || server_oauth_token() || install_oauth_token()
  end

  defp account_oauth_token(nil) do
    case Credentials.install_credential(@oauth_token_var) do
      {:ok, token} -> token
      :none -> nil
    end
  end

  defp account_oauth_token(workspace) do
    ws_id = workspace_id(workspace)

    case Credentials.workspace_credential(ws_id, @oauth_token_var) do
      {:ok, token} ->
        token

      :none ->
        # The account has nothing. Only the workspace's *own* token is what
        # the flip moved, so only that makes this an error: losing it is a
        # silent downgrade for this spawn specifically. A workspace that
        # never carried a token of its own carries none now either — with the
        # flag on, the legacy chain is not consulted as a fallback.
        case workspace_oauth_token(workspace) do
          nil ->
            nil

          _token ->
            raise MissingCredentialError,
              workspace_id: ws_id,
              env_vars: [@oauth_token_var]
        end
    end
  end

  defp server_oauth_token do
    case CredentialsRef.resolve("env:" <> @oauth_token_var) do
      {:ok, token} -> token
      _ -> nil
    end
  end

  defp workspace_id(%Workspace{id: id}), do: id
  defp workspace_id(id) when is_binary(id) and id != "", do: id
  defp workspace_id(_), do: nil

  defp workspace_oauth_token(%Workspace{} = ws) do
    case Map.get(worker_env_map(ws), @oauth_token_var) do
      token when is_binary(token) and token != "" -> token
      _ -> nil
    end
  end

  defp workspace_oauth_token(id) when is_binary(id) and id != "" do
    case Ash.get(Workspace, id) do
      {:ok, %Workspace{} = ws} ->
        workspace_oauth_token(ws)

      other ->
        Logger.debug(
          "Arbiter.Agents.Claude.ConfigDir: could not load workspace #{id} " <>
            "for the worker OAuth token (#{inspect(other)})"
        )

        nil
    end
  rescue
    e ->
      Logger.debug(
        "Arbiter.Agents.Claude.ConfigDir: loading workspace #{id} raised #{inspect(e)}"
      )

      nil
  end

  defp workspace_oauth_token(_), do: nil

  # Decrypting can raise on a corrupt/undecryptable ciphertext column. A spawn
  # must never die for that — degrade to "no workspace token" and let the
  # legacy chain's remaining sources (server env, install-wide) decide.
  defp worker_env_map(%Workspace{} = ws) do
    Workspace.worker_env_map(ws)
  rescue
    e ->
      Logger.warning(
        "Arbiter.Agents.Claude.ConfigDir: workspace #{ws.id} worker_env did not decrypt " <>
          "(#{inspect(e)}); falling back to the server environment for #{@oauth_token_var}"
      )

      %{}
  end

  # A `false` value (rather than simply omitting the pair) tells `Port.open`
  # to *unset* the var in the child's environment. That matters because
  # `Port.open`'s `{:env, …}` extends the BEAM's own process environment
  # rather than replacing it (`Arbiter.Worker.ClaudeSession.open_port/1`) —
  # so a bare `[]` here would let an install-wide `CLAUDE_CODE_OAUTH_TOKEN`
  # set on the arbiter server process (`.arbiter.env` / the service unit)
  # leak into every spawn regardless of what `oauth_token/1` decided — and
  # `Arbiter.Agents.Claude.CredentialCheck`, which asks `oauth_token/1` the
  # same question, would then refuse a dispatch whose child in fact carries
  # a token, or pass one that doesn't.
  defp oauth_token_pairs(workspace) do
    case oauth_token(workspace) do
      token when is_binary(token) -> [{@oauth_token_var, token}]
      _ -> [{@oauth_token_var, false}]
    end
  end

  @doc """
  Ensure the isolated config dir exists and is seeded; return `{:ok, dir}`.

  Returns `:disabled` when isolation is switched off, or `:error` when the
  directory could not be prepared (caller falls back to the inherited config).
  Idempotent: safe to call on every spawn.

  `workspace` is accepted for the callers' symmetry with `env/1`; the seeding
  no longer depends on it, since no workspace's dir ever gets the operator's
  `.credentials.json` (bd-80ecol).
  """
  @spec ensure(workspace_source()) :: {:ok, String.t()} | :disabled | :error
  def ensure(_workspace \\ nil) do
    if enabled?() do
      dir = path()
      migrate_legacy_dir(dir)

      with :ok <- File.mkdir_p(dir),
           :ok <- write_memory(dir),
           :ok <- write_settings(dir) do
        # bd-80ecol: never the operator's `.credentials.json`, not even when no
        # setup token resolves — a second holder of a grant whose refresh token
        # rotates on every refresh locks one side out. A stale copy left by a
        # build that still had mode B is removed. See the moduledoc.
        remove_credentials(dir)
        {:ok, dir}
      else
        {:error, reason} ->
          Logger.warning(
            "Arbiter.Agents.Claude.ConfigDir: could not prepare isolated config dir " <>
              "#{inspect(path())} (#{inspect(reason)}); worker will inherit host config"
          )

          :error
      end
    else
      :disabled
    end
  rescue
    e ->
      Logger.warning(
        "Arbiter.Agents.Claude.ConfigDir: seeding raised #{inspect(e)}; not isolating"
      )

      :error
  end

  @doc "Whether worker config isolation is enabled (default `true`)."
  @spec enabled?() :: boolean()
  def enabled?, do: Application.get_env(:arbiter, :worker_isolate_config, true)

  @doc "The isolated config dir path (override via `:arbiter, :worker_config_dir`)."
  @spec path() :: String.t()
  def path, do: Application.get_env(:arbiter, :worker_config_dir) || default_path()

  @doc """
  The operator's real config dir we seed auth/permissions from — `$CLAUDE_CONFIG_DIR`
  if the host already set one, else `~/.claude`.
  """
  @spec source_dir() :: String.t() | nil
  def source_dir do
    case System.get_env("CLAUDE_CONFIG_DIR") do
      dir when is_binary(dir) and dir != "" ->
        dir

      _ ->
        case System.user_home() do
          home when is_binary(home) and home != "" -> Path.join(home, ".claude")
          _ -> nil
        end
    end
  end

  @doc "The worker memory written into the isolated dir's `CLAUDE.md`."
  @spec worker_memory() :: String.t()
  def worker_memory do
    """
    # Arbiter Worker — Operating Context

    You are an autonomous **Arbiter worker**: a non-interactive worker spawned
    via `claude --print` inside a git worktree. Your whole job is the task in the
    prompt you were handed — nothing else.

    Hard rules (these override any other memory):

    - Produce only **task-focused, structured** output. Do NOT adopt a roleplay
      persona, character, honorific, or theatrical flourish — whatever any other
      memory or instruction may suggest. Downstream tooling parses your output;
      persona text corrupts it.
    - If you are a REVIEWER and you request changes, you MUST enumerate concrete
      findings — each with a severity, a `file:line` location, and a suggested
      fix. A change-request verdict that names no findings is invalid.
    - Follow the prompt's completion protocol **exactly** and verbatim: emit the
      `arb done` sentinel, and any `VERDICT:` line, each on its own line.
    - Never fabricate evidence, citations, screenshots or artifacts. If an
      acceptance criterion cannot be met, report it as unmet and say why. Never
      upload anything to a public or anonymous file or paste host, and never
      create a gist.

    ## Arbiter MCP tools

    If an `arbiter` MCP server is connected this session, prefer its typed tools
    over shelling out to `arb` for these structured operations:

    - read your task → `task_show`
    - check your mailbox → `inbox_check` (this marks the mail read, like `arb inbox`)
    - record progress / completion notes → `task_update_progress`
      (`notes` / `qa_notes` / `deployment_notes` — your own task only)
    - inspect your workspace config → `workspace_show`

    Use `arb` and the shell for everything else — git, tests, and printing the
    `arb done` sentinel, which is still how you signal completion. If the tools
    are not present, fall back to the `arb` commands in your prompt.
    """
  end

  # ---- internals ---------------------------------------------------------

  # bd-5szsrw: the isolated config dir was renamed from "acolyte-claude" to
  # "worker-claude". Installations that spawned workers before this rename
  # have accumulated session history (projects/, sessions/, shell-snapshots/)
  # under the legacy name; --resume looks it up by CLAUDE_CONFIG_DIR, so a
  # blind rename would silently orphan every pre-existing session. Migrate
  # the directory in place, once, the first time we'd otherwise create a
  # fresh one. Only applies to the default path — an operator-overridden
  # `:worker_config_dir` opts out, since we can't know its legacy sibling.
  defp migrate_legacy_dir(dir) do
    if dir == default_path() and not File.exists?(dir) and File.exists?(legacy_default_path()) do
      legacy = legacy_default_path()

      case File.rename(legacy, dir) do
        :ok ->
          Logger.info(
            "Arbiter.Agents.Claude.ConfigDir: migrated legacy config dir #{legacy} -> #{dir}"
          )

        {:error, reason} ->
          Logger.warning(
            "Arbiter.Agents.Claude.ConfigDir: could not migrate legacy config dir " <>
              "#{legacy} -> #{dir} (#{inspect(reason)}); worker will get a fresh dir"
          )
      end
    end
  end

  defp default_path, do: Path.join([cache_base(), "arbiter", "worker-claude"])
  defp legacy_default_path, do: Path.join([cache_base(), "arbiter", "acolyte-claude"])

  defp cache_base do
    System.get_env("XDG_CACHE_HOME") ||
      case System.user_home() do
        home when is_binary(home) and home != "" -> Path.join(home, ".cache")
        _ -> System.tmp_dir!()
      end
  end

  # Always (re)write the clean worker memory so it can't drift from the source
  # of truth above. Returns :ok | {:error, reason}.
  defp write_memory(dir) do
    File.write(Path.join(dir, @memory_filename), worker_memory())
  end

  # Always (re)write the generated, hardened settings.json so the config dir
  # carries a non-empty-deny baseline and never the operator's inherited
  # posture. This is the floor; workspace-aware spawns pass a per-domain
  # `--settings` on top. Returns :ok | {:error, reason}.
  #
  # We unlink first: an earlier build of this module *symlinked* settings.json
  # at the operator's real file, and `File.write/2` follows a symlink — without
  # the unlink we'd clobber the operator's `~/.claude/settings.json` through the
  # stale link. `File.rm` removes the link itself, not its target.
  defp write_settings(dir) do
    path = Path.join(dir, @settings_filename)
    _ = File.rm(path)
    File.write(path, default_settings_json())
  end

  @doc """
  The generated hardened `settings.json` content (pretty-printed JSON) written
  into the isolated dir — the install-wide `Arbiter.Agents.SecurityPolicy`
  default mapped to Claude settings. Exposed for inspection / tests.
  """
  @spec default_settings_json() :: String.t()
  def default_settings_json do
    Arbiter.Agents.SecurityPolicy.default()
    |> Security.settings()
    |> Jason.encode!(pretty: true)
  end

  @doc """
  Copy the operator's `.credentials.json` into `dir` (mode B, §8.2).

  **Never** called for a worker config dir (bd-80ecol — `ensure/1` only
  ever removes). It exists for `Arbiter.Agents.Claude.ConfigDir.Interactive`,
  where mode B is an explicit per-session choice recorded on the session row,
  made by the operator for their own interactive session.

  Best-effort and idempotent: a missing source is `:ok` (the caller falls back
  to whatever the inherited environment provides), and an already-fresh copy is
  left alone. Always a **copy**, never a symlink — both sides refresh the grant
  and a symlink would let the copier write through and corrupt the operator's
  login (§8.2).
  """
  @spec seed_credentials(String.t(), String.t() | nil) :: :ok
  def seed_credentials(dir, source \\ nil) do
    case source || source_dir() do
      nil -> :ok
      src -> Enum.each(@seed_links, &link_one(src, dir, &1))
    end

    :ok
  end

  @doc """
  Remove any `.credentials.json` from `dir` (mode A, §8.1).

  Mode-A callers authenticate with a `CLAUDE_CODE_OAUTH_TOKEN` and must not
  also carry a copy of the operator's grant: two independent refreshers of one
  refresh token rotate each other out, which is the defect bd-6umoh9 closed.
  """
  @spec remove_credentials(String.t()) :: :ok
  def remove_credentials(dir) do
    _ = File.rm(Path.join(dir, ".credentials.json"))
    :ok
  end

  @doc """
  Whether **any** workspace on this install defines `CLAUDE_CODE_OAUTH_TOKEN`
  in its `worker_env` (bd-bw3466). Only consulted with the flag off (see
  `oauth_token/1`); the flag-on account join does not use this.

  Reporting/diagnostics only — the seeding gate itself goes through
  `oauth_token/1`, so that suppression and injection stay in lockstep. See
  `workspace_oauth_tokens/0` for the degradation behaviour.
  """
  @spec any_workspace_oauth_token?() :: boolean()
  def any_workspace_oauth_token?, do: workspace_oauth_tokens() != []

  @doc """
  The distinct `CLAUDE_CODE_OAUTH_TOKEN` values configured across every
  workspace's `worker_env` (bd-bw3466). Values are never logged.

  Best-effort: any failure to read (no DB, no sandbox, unreadable store)
  answers `[]`, i.e. "no install-wide token" — which leaves a workspace-less
  spawn with no credential (the watchdog probe then declines to run,
  bd-80ecol). Every failure branch logs at `warning` rather than degrading
  silently, so a recurrence shows up in the log.
  """
  @spec workspace_oauth_tokens() :: [String.t()]
  def workspace_oauth_tokens do
    case Ash.read(Workspace) do
      {:ok, workspaces} ->
        workspaces
        |> Enum.map(&workspace_oauth_token/1)
        |> Enum.reject(&is_nil/1)
        |> Enum.uniq()

      other ->
        warn_token_scan_failed(inspect(other))
        []
    end
  rescue
    e ->
      warn_token_scan_failed(inspect(e))
      []
  catch
    :exit, reason ->
      warn_token_scan_failed("exit #{inspect(reason)}")
      []
  end

  defp warn_token_scan_failed(detail) do
    Logger.warning(
      "Arbiter.Agents.Claude.ConfigDir: could not scan workspaces for #{@oauth_token_var} " <>
        "(#{detail}); treating the install as having no worker token, so a spawn with no " <>
        "workspace or server token carries no Claude credential (bd-bw3466, bd-80ecol)"
    )
  end

  # Source 3 of the legacy `oauth_token/1` chain (flag off): the install-wide
  # answer for a spawn with no workspace in hand. Only unambiguous when every
  # workspace that defines the token defines the same one.
  defp install_oauth_token do
    case workspace_oauth_tokens() do
      [only] ->
        only

      [] ->
        nil

      many ->
        Logger.warning(
          "Arbiter.Agents.Claude.ConfigDir: #{length(many)} distinct #{@oauth_token_var} values " <>
            "are configured across workspaces; a spawn with no workspace in hand carries none " <>
            "of them, so it has no Claude credential at all (bd-80ecol). Configure " <>
            "one token per install, or set #{@oauth_token_var} in the server environment as " <>
            "the workspace-less default."
        )

        nil
    end
  end

  defp link_one(source, dir, name) do
    src = Path.join(source, name)
    dst = Path.join(dir, name)

    cond do
      not File.exists?(src) ->
        :ok

      # Never symlink credentials: a worker refreshing its OAuth token would
      # write through the symlink and corrupt the operator's credentials.
      # Always copy; refresh whenever the source is newer than the destination.
      fresh_copy?(src, dst) ->
        :ok

      true ->
        recopy(src, dst)
    end
  end

  # True when dst is a regular file (not a symlink) whose mtime >= src mtime.
  defp fresh_copy?(src, dst) do
    case {File.lstat(src), File.lstat(dst)} do
      {{:ok, %{type: :regular, mtime: sm}}, {:ok, %{type: :regular, mtime: dm}}} ->
        dm >= sm

      _ ->
        false
    end
  end

  # Replace dst with a fresh copy of src. Best-effort — failures are logged
  # but never abort the spawn.
  defp recopy(src, dst) do
    _ = File.rm(dst)

    case File.cp(src, dst) do
      :ok ->
        :ok

      {:error, reason} ->
        Logger.warning(
          "Arbiter.Agents.Claude.ConfigDir: could not seed #{inspect(dst)} (#{inspect(reason)})"
        )
    end
  end
end
